language: go

go:
  - master

before_install:
  - go get github.com/go-gem/gem
  - go get github.com/mattn/goveralls
  - go get github.com/NYTimes/gziphandler

script:
  - $HOME/gopath/bin/goveralls -service=travis-ci